# Generated by Django 5.1 on 2026-03-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='contact',
            field=models.ManyToManyField(blank=True, to='contact.contact'),
        ),
        migrations.AddField(
            model_name='bank',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='contact.address'),
        ),
        migrations.AddField(
            model_name='bank',
            name='notes_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_notes', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='bank',
            name='notes_interest_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_interest', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.bank'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account_asset', to='accounts.account'),
        ),
    ]
