# Generated by Django 5.1 on 2026-03-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('department', '0002_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_allocations', to='party.staff'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requests', to='party.staff'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounts.budgetrequest'),
        ),
        migrations.AddField(
            model_name='budgettype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_types', to='department.department'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='budget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.budgettype'),
        ),
        migrations.AddField(
            model_name='account',
            name='accounttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.charts_of_account'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_reports', to='department.branch'),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.expensetype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transactiondoc',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.transactiondoc'),
        ),
        migrations.AddField(
            model_name='transactionrequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transactionrequest',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.transactionrequesttype'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('bank', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='budgettype',
            unique_together={('name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('accounttype', 'name', 'content_type', 'object_id')},
        ),
    ]
