# Generated by Django 5.1 on 2026-03-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcompanydocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='historicalcompanycontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcompanycontact',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcompanydocument',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcompanydocument',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldocumenttype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicaldocumenttype',
            name='history_user',
        ),
    ]
