# Generated by Django 5.1 on 2026-03-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companycontact_company_and_more'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='companies', to='contact.contact'),
        ),
        migrations.DeleteModel(
            name='CompanyContact',
        ),
        migrations.DeleteModel(
            name='CompanyDocument',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='HistoricalCompanyContact',
        ),
        migrations.DeleteModel(
            name='HistoricalCompanyDocument',
        ),
        migrations.DeleteModel(
            name='HistoricalDocumentType',
        ),
    ]
