# Generated by Django 5.1 on 2026-03-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contact', '0001_initial'),
        ('department', '0002_initial'),
        ('hrm', '0001_initial'),
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemanagement',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to='party.occupation'),
        ),
        migrations.AddField(
            model_name='employeemanagement',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_management', to='party.staff'),
        ),
        migrations.AddField(
            model_name='employeemanagement',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='employees', to='accounts.tax'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='employee_deduction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='employee_benefit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='employeesalaryrule',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rule', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='employeeseverancepackage',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='severance_package', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to='contact.country'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leaves', to='party.staff'),
        ),
        migrations.AddField(
            model_name='leave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='approval_by',
            field=models.ManyToManyField(blank=True, related_name='approved_leave_types', to='party.staff'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_types', to='department.department'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hrm.leavetype'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hrm.leavetype'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='assigned_branch',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='department.branch'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='assigned_department',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='department.department'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_meetings', to='party.staff'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='hrm.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_meetings', to='department.room'),
        ),
        migrations.AddField(
            model_name='meetingsubject',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_subjects', to='party.staff'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='hrm.meetingsubject'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='approved_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_overtimes', to='party.staff'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='hrm.attendance'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_overtimes', to='party.staff'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='party.staff'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='approved_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payroll_details', to='party.staff'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_details', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hrm.payroll'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to='party.staff'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_employee_shifts', to='department.branch'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_shifts', to='hrm.holiday'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_shifts', to='hrm.leave'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_employee_shifts', to='department.shift'),
        ),
        migrations.AddField(
            model_name='scheduledshift',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to='party.staff'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hrm.scheduledshift'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skillset',
            field=models.ManyToManyField(blank=True, to='hrm.skill'),
        ),
        migrations.AddField(
            model_name='performanceevaluation',
            name='skills_assessed',
            field=models.ManyToManyField(blank=True, related_name='evaluations', to='hrm.skill'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='hrm.skill'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='deduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='hrm.employee_deduction'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hrm.employeemanagement'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='loan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hrm.loantype'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to='party.staff'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='department.department'),
        ),
        migrations.AddField(
            model_name='employeemanagement',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.vacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='employeebankdetails',
            unique_together={('employee', 'bank', 'account_number')},
        ),
        migrations.AlterUniqueTogether(
            name='employee_deduction',
            unique_together={('employee', 'deduction')},
        ),
        migrations.AlterUniqueTogether(
            name='employee_benefit',
            unique_together={('employee', 'benefit')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='payrolldetail',
            unique_together={('payroll', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
    ]
