# Generated by Django 5.1 on 2026-03-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='companies', to='contact.contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='tradecountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='contact.country'),
        ),
        migrations.AddField(
            model_name='domain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='company.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='company.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='company.paymentclass'),
        ),
    ]
