# Generated by Django 5.1 on 2026-03-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('contact', '0001_initial'),
        ('crm', '0001_initial'),
        ('department', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to='party.staff'),
        ),
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='party.client'),
        ),
        migrations.AddField(
            model_name='deal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='department.department'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to='party.staff'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='converted_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_prospects', to='party.client'),
        ),
        migrations.AddField(
            model_name='deal',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.prospect'),
        ),
        migrations.AddField(
            model_name='prospect_company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_companies', to='contact.country'),
        ),
        migrations.AddField(
            model_name='prospect_company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_companies', to='company.industry'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.prospect_company'),
        ),
        migrations.AddField(
            model_name='prospectpipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_positions', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='prospectpipelinestage',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stage', to='crm.prospect'),
        ),
        migrations.AddField(
            model_name='salemember',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_memberships', to='party.staff'),
        ),
        migrations.AddField(
            model_name='saleteam',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_teams', to='department.department'),
        ),
        migrations.AddField(
            model_name='saleteam',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sale_teams', to='party.staff'),
        ),
        migrations.AddField(
            model_name='salemember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.saleteam'),
        ),
        migrations.AddField(
            model_name='prospect_company',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_companies', to='crm.saleteam'),
        ),
        migrations.AddField(
            model_name='deal',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.saleteam'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='crm.saleteam'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='prospectpipelinestage',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='pipelinetransition',
            name='from_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='pipelinetransition',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='deal',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='territory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='department.branch'),
        ),
        migrations.AddField(
            model_name='territory',
            name='parent_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.territory'),
        ),
        migrations.AddField(
            model_name='saleteam',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_teams', to='crm.territory'),
        ),
        migrations.AlterUniqueTogether(
            name='salemember',
            unique_together={('team', 'staff')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('pipeline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinetransition',
            unique_together={('from_stage', 'to_stage')},
        ),
    ]
