# Generated by Django 5.1 on 2026-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Code'),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='phone_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Code'),
        ),
    ]
