# Generated by Django 5.1 on 2026-03-12 14:55

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='max_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum tax to charge after percentage calculation (0 = no cap).', max_digits=18, verbose_name='Maximum Tax Amount'),
        ),
        migrations.AddField(
            model_name='historicaltax',
            name='min_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum tax to charge after percentage calculation (0 = no floor).', max_digits=18, verbose_name='Minimum Tax Amount'),
        ),
        migrations.AddField(
            model_name='tax',
            name='max_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum tax to charge after percentage calculation (0 = no cap).', max_digits=18, verbose_name='Maximum Tax Amount'),
        ),
        migrations.AddField(
            model_name='tax',
            name='min_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum tax to charge after percentage calculation (0 = no floor).', max_digits=18, verbose_name='Minimum Tax Amount'),
        ),
        migrations.AlterField(
            model_name='historicaltax',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='historicaltax',
            name='tax_type',
            field=models.CharField(choices=[('percent', 'Percentage')], default='percent', max_length=10, verbose_name='Tax Type'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], decimal_places=2, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount_default',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], decimal_places=2, max_digits=20, null=True, verbose_name='Amount (Default Currency)'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount_default_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], default='GHS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('percent', 'Percentage')], default='percent', max_length=10, verbose_name='Tax Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], decimal_places=2, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_default',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], decimal_places=2, max_digits=20, null=True, verbose_name='Amount (Default Currency)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_default_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY')], default='GHS', editable=False, max_length=3, null=True),
        ),
    ]
