from apps.common.api import build_model_serializer
from apps.hrm.models import Attendance, Benefit, Deduction, Employee_Benefit, Employee_Deduction, EmployeeBankDetails, EmployeeManagement, EmployeeSalaryRule, EmployeeSeverancePackage, EmployeeSkill, Holiday, Leave, LeaveBalance, LeaveType, LoanType, Meeting, MeetingSubject, OverTime, Payroll, PayrollDetail, PerformanceEvaluation, ScheduledShift, Skill, StaffLoan, Vacancy

SkillSerializer = build_model_serializer(Skill)
HolidaySerializer = build_model_serializer(Holiday)
MeetingSubjectSerializer = build_model_serializer(MeetingSubject)
MeetingSerializer = build_model_serializer(Meeting)
VacancySerializer = build_model_serializer(Vacancy)
DeductionSerializer = build_model_serializer(Deduction)
BenefitSerializer = build_model_serializer(Benefit)
EmployeeManagementSerializer = build_model_serializer(EmployeeManagement)
EmployeeSalaryRuleSerializer = build_model_serializer(EmployeeSalaryRule)
EmployeeSeverancePackageSerializer = build_model_serializer(EmployeeSeverancePackage)
EmployeeDeductionSerializer = build_model_serializer(Employee_Deduction)
EmployeeBenefitSerializer = build_model_serializer(Employee_Benefit)
EmployeeSkillSerializer = build_model_serializer(EmployeeSkill)
EmployeeBankDetailsSerializer = build_model_serializer(EmployeeBankDetails)
LeaveTypeSerializer = build_model_serializer(LeaveType)
LeaveSerializer = build_model_serializer(Leave, read_only_fields=("days",))
LeaveBalanceSerializer = build_model_serializer(LeaveBalance, read_only_fields=("remaining_days",))
ScheduledShiftSerializer = build_model_serializer(ScheduledShift)
AttendanceSerializer = build_model_serializer(Attendance)
OverTimeSerializer = build_model_serializer(OverTime)
LoanTypeSerializer = build_model_serializer(LoanType)
StaffLoanSerializer = build_model_serializer(StaffLoan)
PayrollSerializer = build_model_serializer(Payroll)
PayrollDetailSerializer = build_model_serializer(PayrollDetail)
PerformanceEvaluationSerializer = build_model_serializer(PerformanceEvaluation)
