from apps.common.api import build_model_viewset
from apps.hrm.api.serializers import AttendanceSerializer, BenefitSerializer, DeductionSerializer, EmployeeBankDetailsSerializer, EmployeeBenefitSerializer, EmployeeDeductionSerializer, EmployeeManagementSerializer, EmployeeSalaryRuleSerializer, EmployeeSeverancePackageSerializer, EmployeeSkillSerializer, HolidaySerializer, LeaveBalanceSerializer, LeaveSerializer, LeaveTypeSerializer, LoanTypeSerializer, MeetingSerializer, MeetingSubjectSerializer, OverTimeSerializer, PayrollDetailSerializer, PayrollSerializer, PerformanceEvaluationSerializer, ScheduledShiftSerializer, SkillSerializer, StaffLoanSerializer, VacancySerializer
from apps.hrm.models import Attendance, Benefit, Deduction, Employee_Benefit, Employee_Deduction, EmployeeBankDetails, EmployeeManagement, EmployeeSalaryRule, EmployeeSeverancePackage, EmployeeSkill, Holiday, Leave, LeaveBalance, LeaveType, LoanType, Meeting, MeetingSubject, OverTime, Payroll, PayrollDetail, PerformanceEvaluation, ScheduledShift, Skill, StaffLoan, Vacancy

SkillViewSet = build_model_viewset(Skill, SkillSerializer, search_fields=("name",))
HolidayViewSet = build_model_viewset(Holiday, HolidaySerializer, search_fields=("name",), filterset_fields=("country", "is_public"), ordering_fields=("date",))
MeetingSubjectViewSet = build_model_viewset(MeetingSubject, MeetingSubjectSerializer, search_fields=("subject",))
MeetingViewSet = build_model_viewset(Meeting, MeetingSerializer, filterset_fields=("room", "subject", "status"), ordering_fields=("date",))
VacancyViewSet = build_model_viewset(Vacancy, VacancySerializer, search_fields=("title",), filterset_fields=("department", "is_filled"))
DeductionViewSet = build_model_viewset(Deduction, DeductionSerializer, search_fields=("name",))
BenefitViewSet = build_model_viewset(Benefit, BenefitSerializer, search_fields=("name",))
EmployeeManagementViewSet = build_model_viewset(EmployeeManagement, EmployeeManagementSerializer, filterset_fields=("staff", "is_employed", "vacancy"))
EmployeeSalaryRuleViewSet = build_model_viewset(EmployeeSalaryRule, EmployeeSalaryRuleSerializer, filterset_fields=("employee",))
EmployeeSeverancePackageViewSet = build_model_viewset(EmployeeSeverancePackage, EmployeeSeverancePackageSerializer, filterset_fields=("employee",))
EmployeeDeductionViewSet = build_model_viewset(Employee_Deduction, EmployeeDeductionSerializer, filterset_fields=("employee", "deduction"))
EmployeeBenefitViewSet = build_model_viewset(Employee_Benefit, EmployeeBenefitSerializer, filterset_fields=("employee", "benefit"))
EmployeeSkillViewSet = build_model_viewset(EmployeeSkill, EmployeeSkillSerializer, filterset_fields=("employee", "skill"))
EmployeeBankDetailsViewSet = build_model_viewset(EmployeeBankDetails, EmployeeBankDetailsSerializer, filterset_fields=("employee", "bank"))
LeaveTypeViewSet = build_model_viewset(LeaveType, LeaveTypeSerializer, search_fields=("name",), filterset_fields=("department", "is_paid"))
LeaveViewSet = build_model_viewset(Leave, LeaveSerializer, filterset_fields=("staff", "leave_type", "status"), ordering_fields=("start_date",))
LeaveBalanceViewSet = build_model_viewset(LeaveBalance, LeaveBalanceSerializer, filterset_fields=("employee", "leave_type", "year"))
ScheduledShiftViewSet = build_model_viewset(ScheduledShift, ScheduledShiftSerializer, filterset_fields=("employee", "shift", "branch", "is_onleave"))
AttendanceViewSet = build_model_viewset(Attendance, AttendanceSerializer, filterset_fields=("employee", "branch", "status", "date"))
OverTimeViewSet = build_model_viewset(OverTime, OverTimeSerializer, filterset_fields=("attendance", "status", "requested_by"))
LoanTypeViewSet = build_model_viewset(LoanType, LoanTypeSerializer, search_fields=("name",))
StaffLoanViewSet = build_model_viewset(StaffLoan, StaffLoanSerializer, filterset_fields=("employee", "loan_type", "approval_status", "status"))
PayrollViewSet = build_model_viewset(Payroll, PayrollSerializer, filterset_fields=("status", "staff"), ordering_fields=("date",))
PayrollDetailViewSet = build_model_viewset(PayrollDetail, PayrollDetailSerializer, filterset_fields=("payroll", "employee", "status"))
PerformanceEvaluationViewSet = build_model_viewset(PerformanceEvaluation, PerformanceEvaluationSerializer, filterset_fields=("employee", "evaluator"), ordering_fields=("date",))
