# Generated by Django 5.1 on 2026-03-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('department', '0001_initial'),
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='warehouse_unit',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_warehouse': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_branches', to='department.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='departments', to='contact.contact'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_marked_up_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markup_children', to='department.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='department.department'),
        ),
        migrations.AddField(
            model_name='room',
            name='assigned_branch',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='department.branch'),
        ),
        migrations.AddField(
            model_name='room',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='roomassignedstaff', to='party.staff'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='contact.address'),
        ),
        migrations.AddField(
            model_name='room',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelfing',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchshelf', to='department.branch'),
        ),
        migrations.AddField(
            model_name='shelfing',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelves', to='department.room'),
        ),
        migrations.AddField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='department.department'),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'departmenttype')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='shelfing',
            unique_together={('branch', 'shelf')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('shift_types', 'department')},
        ),
    ]
