"""
apps/accounting/models.py

Double-entry accounting system for the ERP.

Hierarchy:
    ChartsOfAccount  ←  Account  ←  Transaction
                                 ←  JournalEntryLine
    TransactionDoc   ←  Transaction
    JournalEntry     ←  JournalEntryLine

Auto-account creation:
    post_save signals on Branch, StaffProfile, ClientProfile, SupplierProfile,
    Tax, Bank, BankAccount fire create_account_instance() which creates the
    correct Account rows and back-links them.

COA bootstrap:
    post_save on Company calls load_initial_account_data() to bulk-create the
    full default chart of accounts for each new tenant.
"""

from decimal import Decimal
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.validators import int_list_validator
from django.db import models
from django.db.models import Avg, Max, Sum, Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import CurrencyField, MoneyField
from djmoney.money import Money

from apps.common.models import TenantAwareModel, DEFAULT_CURRENCY, ALLOWED_CURRENCIES, CURRENCY_CHOICES

# ─────────────────────────────────────────────────────────────────────────────
# Chart of Accounts
# ─────────────────────────────────────────────────────────────────────────────

class ChartsOfAccount(TenantAwareModel):
    """
    Defines the account types available in the ledger.
    acc_number is auto-generated by account_type series on first save.
    Normal balance is auto-derived from account_type.
    """
    ACCOUNT_TYPE_CHOICES = (
        ("Assets", _("Assets")),
        ("Expenses", _("Expenses")),
        ("Liabilities", _("Liabilities")),
        ("Revenues/Income", _("Revenues / Income")),
        ("Capital/Equity", _("Capital / Equity")),
    )
    BALANCE_TYPE_CHOICES = (
        ("Debit", _("Debit")),
        ("Credit", _("Credit")),
    )
    # Series ranges: Assets 10M, Liabilities 20M, Capital 30M, Revenue 40M, Expenses 50M
    SERIES_STARTS = {
        "Assets": 10100000,
        "Liabilities": 20100000,
        "Capital/Equity": 30100000,
        "Revenues/Income": 40100000,
        "Expenses": 50100000,
    }
    DEBIT_TYPES = {"Assets", "Expenses"}
    CREDIT_TYPES = {"Liabilities", "Revenues/Income", "Capital/Equity"}

    acc_number = models.PositiveIntegerField(_("Account Number"), editable=False)
    name = models.CharField(_("Account Name"), max_length=100, unique=True)
    description = models.TextField(_("Description"), blank=True, null=True)
    account_type = models.CharField(
        _("Account Type"), max_length=20, choices=ACCOUNT_TYPE_CHOICES
    )
    account_balance_type = models.CharField(
        _("Normal Balance"), max_length=10, choices=BALANCE_TYPE_CHOICES, editable=False
    )
    is_system_account = models.BooleanField(
        _("System Account?"), default=False,
        help_text=_("System accounts cannot be deleted.")
    )
    allow_direct_posting = models.BooleanField(_("Allow Direct Posting?"), default=True)

    class Meta:
        verbose_name = _("Charts of Account")
        verbose_name_plural = _("Charts of Accounts")
        ordering = ["acc_number"]

    def __str__(self):
        return f"{self.acc_number} — {self.name}"

    def get_absolute_url(self):
        return reverse("coa_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        # Auto-derive normal balance
        if self.account_type in self.DEBIT_TYPES:
            self.account_balance_type = "Debit"
        elif self.account_type in self.CREDIT_TYPES:
            self.account_balance_type = "Credit"
        else:
            raise ValidationError(f"Invalid account type: {self.account_type}")

        # Auto-assign sequential acc_number on creation
        if self._state.adding:
            series_start = self.SERIES_STARTS.get(self.account_type, 10100000)
            step = 1000
            last = ChartsOfAccount.objects.filter(
                account_type=self.account_type
            ).aggregate(Max("acc_number"))["acc_number__max"]
            self.acc_number = (last + step) if last else series_start

        super().save(*args, **kwargs)


# ─────────────────────────────────────────────────────────────────────────────
# Account Ledger
# ─────────────────────────────────────────────────────────────────────────────

class Account(TenantAwareModel):
    """
    Individual ledger account tied to a specific entity (Branch, Tax, Staff…)
    via a GenericForeignKey.  acc_number is derived from the parent COA.
    """
    account_type = models.ForeignKey(
        ChartsOfAccount, verbose_name=_("Chart of Account"),
        on_delete=models.DO_NOTHING, related_name="accounts"
    )
    acc_number = models.PositiveIntegerField(_("Account Number"), editable=False, unique=True)
    name = models.CharField(_("Account Name"), max_length=255, blank=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING)
    object_id = models.UUIDField()
    account_object = GenericForeignKey("content_type", "object_id")
    notes = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = _("Account")
        verbose_name_plural = _("Accounts")
        unique_together = ("object_id", "account_type")
        ordering = ["acc_number"]

    def __str__(self):
        return f"{self.acc_number} — {self.name or self.account_type.name}"

    def get_absolute_url(self):
        return reverse("account_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if self._state.adding:
            coa = ChartsOfAccount.objects.get(pk=self.account_type.pk)
            count = Account.objects.filter(account_type=self.account_type).count()
            self.acc_number = count + 1 + coa.acc_number
        super().save(*args, **kwargs)

    @property
    def running_balance(self):
        """Compute balance from posted transactions."""
        debit = (
            Transaction.objects.filter(account=self, transaction_type="Debit")
            .aggregate(t=Sum("amount_default_currency"))
            .get("t") or Decimal("0")
        )
        credit = (
            Transaction.objects.filter(account=self, transaction_type="Credit")
            .aggregate(t=Sum("amount_default_currency"))
            .get("t") or Decimal("0")
        )
        if self.account_type.account_balance_type == "Debit":
            return debit - credit
        return credit - debit


# ─────────────────────────────────────────────────────────────────────────────
# Transaction Document & Lines
# ─────────────────────────────────────────────────────────────────────────────

class TransactionDoc(TenantAwareModel):
    """
    Header record for a batch of transactions (e.g. payment, invoice posting).
    Linked to the originating business document via GenericFK.
    """
    date = models.DateTimeField(_("Date"), default=timezone.now)
    description = models.TextField(_("Description"))
    reference = models.CharField(_("Reference"), max_length=100, blank=True)
    posted = models.BooleanField(_("Posted?"), default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.UUIDField(null=True, blank=True)
    source_document = GenericForeignKey("content_type", "object_id")

    class Meta:
        verbose_name = _("Transaction Document")
        verbose_name_plural = _("Transaction Documents")
        ordering = ["-date"]

    def __str__(self):
        return f"{self.reference or self.id} — {self.description[:50]}"

    def get_absolute_url(self):
        return reverse("transactiondoc_detail", kwargs={"pk": self.pk})


class Transaction(TenantAwareModel):
    """
    Single debit or credit line against an Account.
    Enforces that debits == credits via TransactionDoc grouping.
    """
    TRANSACTION_TYPE_CHOICES = (
        ("Debit", _("Debit")),
        ("Credit", _("Credit")),
    )

    notes = models.ForeignKey(
        TransactionDoc, verbose_name=_("Transaction Document"),
        on_delete=models.CASCADE, related_name="transactions"
    )
    account = models.ForeignKey(
        Account, verbose_name=_("Account"),
        on_delete=models.CASCADE, related_name="account_transactions"
    )
    coa = models.ForeignKey(
        ChartsOfAccount, verbose_name=_("Chart of Account"),
        on_delete=models.CASCADE, related_name="coa_transactions", editable=False
    )
    transaction_type = models.CharField(
        _("Type"), max_length=10, choices=TRANSACTION_TYPE_CHOICES
    )
    amount = MoneyField(
        _("Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    conversion_rate = models.DecimalField(_("Conversion Rate"), max_digits=10, decimal_places=6, default=1)
    amount_default = MoneyField(
        _("Amount (Default Currency)"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    description = models.CharField(_("Description"), max_length=255, blank=True)

    class Meta:
        verbose_name = _("Transaction")
        verbose_name_plural = _("Transactions")
        ordering = ["-notes__date"]

    def __str__(self):
        return f"{self.account.acc_number} | {self.transaction_type} | {self.amount}"

    def save(self, *args, **kwargs):
        if not self.account_id:
            raise ValidationError(_("Account is required."))
        self.coa = self.account.account_type
        self.amount_default = self.amount / self.conversion_rate
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("transaction_detail", kwargs={"pk": self.pk})


# ─────────────────────────────────────────────────────────────────────────────
# Journal Entry (double-entry wrapper)
# ─────────────────────────────────────────────────────────────────────────────

class JournalEntry(TenantAwareModel):
    """
    Double-entry journal entry.  Must have balanced debit/credit lines.
    """
    STATUS_CHOICES = [
        ("draft", _("Draft")),
        ("posted", _("Posted")),
        ("reversed", _("Reversed")),
    ]

    date = models.DateField(_("Entry Date"), default=timezone.now)
    reference = models.CharField(_("Reference"), max_length=100, blank=True)
    description = models.TextField(_("Description"))
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="draft")
    is_reversal = models.BooleanField(_("Is Reversal?"), default=False)
    reversed_entry = models.OneToOneField(
        "self", verbose_name=_("Reversed Entry"), null=True, blank=True,
        on_delete=models.SET_NULL, related_name="reversal"
    )
    transaction_doc = models.OneToOneField(
        TransactionDoc, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="journal_entry"
    )

    class Meta:
        verbose_name = _("Journal Entry")
        verbose_name_plural = _("Journal Entries")
        ordering = ["-date"]

    def __str__(self):
        return f"JE {self.reference or self.id} ({self.date})"

    def get_absolute_url(self):
        return reverse("journalentry_detail", kwargs={"pk": self.pk})

    def post(self):
        """Validate balance and mark as posted."""
        lines = self.lines.all()
        total_debit = sum(l.debit_amount for l in lines if l.debit_amount)
        total_credit = sum(l.credit_amount for l in lines if l.credit_amount)
        if total_debit != total_credit:
            raise ValidationError(
                _("Journal entry is not balanced: debits %(d)s ≠ credits %(c)s") % {
                    "d": total_debit, "c": total_credit
                }
            )
        self.status = "posted"
        self.save()


class JournalEntryLine(TenantAwareModel):
    journal_entry = models.ForeignKey(JournalEntry, on_delete=models.CASCADE, related_name="lines")
    account = models.ForeignKey(Account, on_delete=models.PROTECT, related_name="journal_lines")
    description = models.CharField(_("Description"), max_length=255, blank=True)
    debit_amount = models.DecimalField(_("Debit"), max_digits=20, decimal_places=2, default=0)
    credit_amount = models.DecimalField(_("Credit"), max_digits=20, decimal_places=2, default=0)
    currency = CurrencyField(default=DEFAULT_CURRENCY, choices=CURRENCY_CHOICES)

    class Meta:
        verbose_name = _("Journal Entry Line")
        verbose_name_plural = _("Journal Entry Lines")
        ordering = ["journal_entry", "account__acc_number"]

    def __str__(self):
        return f"{self.account.acc_number} | Dr {self.debit_amount} / Cr {self.credit_amount}"

    def clean(self):
        if self.debit_amount < 0 or self.credit_amount < 0:
            raise ValidationError(_("Debit and credit amounts must be non-negative."))
        if self.debit_amount > 0 and self.credit_amount > 0:
            raise ValidationError(_("A line cannot have both a debit and a credit amount."))
        if self.debit_amount == 0 and self.credit_amount == 0:
            raise ValidationError(_("A line must have either a debit or credit amount > 0."))


# ─────────────────────────────────────────────────────────────────────────────
# Tax
# ─────────────────────────────────────────────────────────────────────────────

class Tax(TenantAwareModel):
    TAX_TYPE_CHOICES = (("percent", _("Percentage")), ("amount", _("Fixed Amount")))

    name = models.CharField(_("Tax Name"), max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    effective_date = models.DateField(_("Effective Date"))
    is_tax_recoverable = models.BooleanField(_("Recoverable Input Tax?"), default=False)
    tax_type = models.CharField(_("Tax Type"), max_length=10, choices=TAX_TYPE_CHOICES, default="percent")
    tax = models.DecimalField(_("Tax Rate / Amount"), max_digits=18, decimal_places=4, default=0)
    min_taxable_amount = models.DecimalField(
        _("Min Taxable Amount"), max_digits=18, decimal_places=2, default=0,
        help_text=_("Only amounts above this threshold are taxable (0 = always applies).")
    )
    max_taxable_amount = models.DecimalField(
        _("Max Taxable Amount"), max_digits=18, decimal_places=2, default=0,
        help_text=_("Tax is capped at this amount (0 = no cap).")
    )
    # Auto-linked accounts set via create_account_instance signal
    tax_payable_account = models.ForeignKey(
        Account, null=True, blank=True, editable=False,
        on_delete=models.SET_NULL,
        limit_choices_to=Q(account_type__name="Taxes Payable"),
        related_name="tax_payable_accounts", verbose_name=_("Tax Payable Account")
    )
    tax_expense_account = models.ForeignKey(
        Account, null=True, blank=True, editable=False,
        on_delete=models.SET_NULL,
        limit_choices_to=Q(account_type__name="Tax Expense"),
        related_name="tax_expense_accounts", verbose_name=_("Tax Expense Account")
    )

    class Meta:
        verbose_name = _("Tax")
        verbose_name_plural = _("Taxes")
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.tax}{'%' if self.tax_type == 'percent' else ''})"

    def get_absolute_url(self):
        return reverse("tax_detail", kwargs={"pk": self.pk})

    def clean(self):
        if self.tax_type == "percent" and not (0 <= self.tax <= 100):
            raise ValidationError(_("Percentage tax must be between 0 and 100."))
        if self.tax_type == "amount" and self.tax < 0:
            raise ValidationError(_("Fixed tax amount must be non-negative."))
        if (self.min_taxable_amount > 0 and self.max_taxable_amount > 0
                and self.min_taxable_amount > self.max_taxable_amount):
            raise ValidationError(_("Min taxable amount must be ≤ max taxable amount."))

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


def calculate_tax_amount(amount: Money, tax_id) -> tuple:
    """
    Return (taxable_amount: Money, tax: Tax).
    The returned taxable_amount is the TAX VALUE itself (not the net).
    """
    if not isinstance(amount, Money):
        raise TypeError("amount must be a Money instance")
    amount = Money(amount.amount, DEFAULT_CURRENCY)
    tax = get_object_or_404(Tax, pk=tax_id)

    if tax.min_taxable_amount > 0 and amount.amount < tax.min_taxable_amount:
        return Money(0, DEFAULT_CURRENCY), tax

    if tax.max_taxable_amount > 0 and amount.amount > tax.max_taxable_amount:
        taxable = Money(tax.max_taxable_amount, DEFAULT_CURRENCY)
    else:
        taxable = amount

    if tax.tax_type == "percent":
        return taxable * (tax.tax / Decimal("100")), tax
    return Money(tax.tax, DEFAULT_CURRENCY), tax


# ─────────────────────────────────────────────────────────────────────────────
# Bank & Bank Account
# ─────────────────────────────────────────────────────────────────────────────

class Bank(TenantAwareModel):
    name = models.CharField(_("Bank Name"), max_length=100, unique=True)
    is_main_branch = models.BooleanField(_("Is Headquarters?"), default=False)
    branch_of = models.ForeignKey(
        "self", verbose_name=_("Branch Of"), on_delete=models.CASCADE,
        null=True, blank=True, related_name="bank_branches"
    )
    swift_code = models.CharField(_("SWIFT / BIC"), max_length=20, blank=True)
    country = models.ForeignKey(
        "contact.Country", verbose_name=_("Country"), on_delete=models.PROTECT,
        null=True, blank=True, related_name="banks"
    )
    # Auto-linked via signal
    notes_payable_account = models.ForeignKey(
        Account, null=True, blank=True, editable=False, on_delete=models.SET_NULL,
        limit_choices_to=Q(account_type__name="Notes Payable"),
        related_name="bank_notes_payable"
    )
    notes_interest_account = models.ForeignKey(
        Account, null=True, blank=True, editable=False, on_delete=models.SET_NULL,
        limit_choices_to=Q(account_type__name="Interest Payable"),
        related_name="bank_interest_payable"
    )

    class Meta:
        verbose_name = _("Bank")
        verbose_name_plural = _("Banks")
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("bank_detail", kwargs={"pk": self.pk})


class BankAccount(TenantAwareModel):
    ACCOUNT_TYPE_CHOICES = (
        ("checking", _("Checking")),
        ("savings", _("Savings")),
        ("current", _("Current")),
        ("fixed_deposit", _("Fixed Deposit")),
    )

    bank = models.ForeignKey(Bank, verbose_name=_("Bank"), on_delete=models.CASCADE, related_name="bank_accounts")
    name = models.CharField(_("Account Name"), max_length=100)
    account_number = models.CharField(
        _("Account Number"), max_length=50, blank=True, null=True,
        validators=[int_list_validator(sep="", message=_("Only digits allowed."))]
    )
    routing_number = models.CharField(
        _("Routing Number"), max_length=30, blank=True, null=True,
        validators=[int_list_validator(sep="", message=_("Only digits allowed."))]
    )
    swift_number = models.CharField(_("SWIFT Number"), max_length=30, blank=True, null=True)
    account_type = models.CharField(
        _("Account Type"), max_length=20, choices=ACCOUNT_TYPE_CHOICES, default="checking"
    )
    currency = CurrencyField(default=DEFAULT_CURRENCY, choices=CURRENCY_CHOICES)
    # Auto-linked via signal
    cash_account = models.ForeignKey(
        Account, null=True, blank=True, editable=False, on_delete=models.SET_NULL,
        limit_choices_to=Q(account_type__name="Current Asset"),
        related_name="bank_account_cash"
    )

    class Meta:
        verbose_name = _("Bank Account")
        verbose_name_plural = _("Bank Accounts")
        unique_together = ("bank", "account_number")
        ordering = ["bank", "name"]

    def __str__(self):
        return f"{self.name} @ {self.bank.name}"

    def get_absolute_url(self):
        return reverse("bankaccount_detail", kwargs={"pk": self.pk})


# ─────────────────────────────────────────────────────────────────────────────
# Payment Base (abstract)
# ─────────────────────────────────────────────────────────────────────────────

class PaymentBase(models.Model):
    PAYMENT_METHOD_CHOICES = (
        ("cash", _("Cash")),
        ("cheque", _("Cheque")),
        ("bank_transfer", _("Bank Transfer")),
        ("mobile_money", _("Mobile Money")),
        ("card", _("Card")),
        ("online", _("Online Payment")),
    )

    payment_method = models.CharField(_("Payment Method"), max_length=20, choices=PAYMENT_METHOD_CHOICES)
    reference = models.CharField(_("Reference"), max_length=250)
    payment_notes = models.TextField(_("Notes"), blank=True, null=True)
    transaction = models.ForeignKey(TransactionDoc, verbose_name=_("Transaction Document"), on_delete=models.CASCADE)
    amount = MoneyField(
        _("Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    payment_date = models.DateTimeField(_("Payment Date"))
    bank_account = models.ForeignKey(
        BankAccount, null=True, blank=True, on_delete=models.SET_NULL,
        verbose_name=_("Bank Account"), related_name="+"
    )

    class Meta:
        abstract = True


# ─────────────────────────────────────────────────────────────────────────────
# Budget
# ─────────────────────────────────────────────────────────────────────────────

class BudgetType(TenantAwareModel):
    """Budget category tied to department with designated approving managers."""
    name = models.CharField(_("Name"), max_length=255)
    description = models.TextField(blank=True, null=True)
    department = models.ForeignKey(
        "department.Department", on_delete=models.PROTECT, verbose_name=_("Department"), related_name="budget_types"
    )
    assigned_approving_managers = models.ManyToManyField(
        "party.StaffProfile", verbose_name=_("Approving Managers"), related_name="approvable_budget_types"
    )

    class Meta:
        verbose_name = _("Budget Type")
        verbose_name_plural = _("Budget Types")
        unique_together = ("name", "department")
        ordering = ["department", "name"]

    def __str__(self):
        return f"{self.name} — {self.department.name}"

    def get_absolute_url(self):
        return reverse("budgettype_detail", kwargs={"pk": self.pk})


class BudgetRequest(TenantAwareModel):
    """Request for budget from any source entity."""
    STATUS_CHOICES = [
        ("pending", _("Pending")),
        ("needs_revision", _("Needs Revision")),
        ("approved", _("Approved")),
        ("rejected", _("Rejected")),
        ("cancelled", _("Cancelled")),
    ]

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.UUIDField()
    source_object = GenericForeignKey("content_type", "object_id")

    budget_type = models.ForeignKey(BudgetType, on_delete=models.PROTECT, related_name="budget_requests")
    amount = MoneyField(
        _("Requested Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    reason = models.TextField(_("Reason"))
    requested_by = models.ForeignKey(
        "party.StaffProfile", on_delete=models.PROTECT, related_name="budget_requests_made"
    )
    date_requested = models.DateField(auto_now_add=True)
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="pending")
    approving_staff = models.ForeignKey(
        "party.StaffProfile", on_delete=models.SET_NULL, null=True, blank=True,
        related_name="budget_requests_approved"
    )
    date_approved = models.DateTimeField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = _("Budget Request")
        verbose_name_plural = _("Budget Requests")
        ordering = ["-date_requested"]

    def __str__(self):
        return f"Budget Request #{self.id} — {self.amount}"

    def get_absolute_url(self):
        return reverse("budgetrequest_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if self.status == "approved" and not self.date_approved:
            self.date_approved = timezone.now()
        super().save(*args, **kwargs)


class BudgetAllocation(TenantAwareModel):
    """Records actual disbursement against an approved BudgetRequest."""
    STATUS_CHOICES = [
        ("pending", _("Pending")),
        ("allocated", _("Allocated")),
        ("cancelled", _("Cancelled")),
    ]

    budget_request = models.ForeignKey(BudgetRequest, on_delete=models.PROTECT, related_name="allocations")
    transaction = models.ForeignKey(
        TransactionDoc, on_delete=models.SET_NULL, null=True, blank=True, related_name="budget_allocations"
    )
    amount = MoneyField(
        _("Allocated Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="pending")
    description = models.TextField(blank=True, null=True)
    allocated_to = models.ForeignKey(
        "party.StaffProfile", on_delete=models.PROTECT, related_name="received_allocations"
    )
    allocated_by = models.ForeignKey(
        "party.StaffProfile", on_delete=models.PROTECT, related_name="given_allocations"
    )

    class Meta:
        verbose_name = _("Budget Allocation")
        verbose_name_plural = _("Budget Allocations")
        ordering = ["-created_at"]

    def __str__(self):
        return f"Allocation {self.id} — {self.amount} to {self.allocated_to}"

    def get_absolute_url(self):
        return reverse("budgetallocation_detail", kwargs={"pk": self.pk})


# ─────────────────────────────────────────────────────────────────────────────
# Expense
# ─────────────────────────────────────────────────────────────────────────────

class ExpenseType(TenantAwareModel):
    name = models.CharField(_("Expense Type"), max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    department = models.ForeignKey(
        "department.Department", on_delete=models.PROTECT, verbose_name=_("Department"), related_name="expense_types"
    )

    class Meta:
        verbose_name = _("Expense Type")
        verbose_name_plural = _("Expense Types")
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("expensetype_detail", kwargs={"pk": self.pk})


class ExpenseReport(TenantAwareModel):
    STATUS_CHOICES = [
        ("draft", _("Draft")),
        ("submitted", _("Submitted")),
        ("approved", _("Approved")),
        ("rejected", _("Rejected")),
        ("completed", _("Completed")),
        ("locked", _("Locked")),
    ]

    expense_type = models.ForeignKey(
        ExpenseType, on_delete=models.PROTECT, verbose_name=_("Expense Type"), related_name="expense_reports"
    )
    budget_allocation = models.ForeignKey(
        BudgetAllocation, on_delete=models.PROTECT,
        verbose_name=_("Budget Allocation"),
        limit_choices_to=Q(status="allocated"),
        related_name="expense_reports",
    )
    amount = MoneyField(
        _("Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    returned_amount = MoneyField(
        _("Returned Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    transaction = models.ForeignKey(
        TransactionDoc, on_delete=models.SET_NULL, null=True, blank=True, related_name="expense_reports"
    )
    description = models.TextField(blank=True, null=True)
    staff = models.ForeignKey(
        "party.StaffProfile", on_delete=models.PROTECT,
        verbose_name=_("Reported By"), related_name="expense_reports"
    )
    incurred_on = models.DateTimeField(_("Incurred On"))
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="draft")
    receipts = models.FileField(_("Receipts"), upload_to="expense_receipts/%Y/%m/", null=True, blank=True)

    class Meta:
        verbose_name = _("Expense Report")
        verbose_name_plural = _("Expense Reports")
        ordering = ["-incurred_on"]

    def __str__(self):
        return f"Expense {self.id} — {self.amount} ({self.expense_type.name})"

    def get_absolute_url(self):
        return reverse("expensereport_detail", kwargs={"pk": self.pk})


# ─────────────────────────────────────────────────────────────────────────────
# Transaction Request (pre-approval workflow)
# ─────────────────────────────────────────────────────────────────────────────

class TransactionRequestType(TenantAwareModel):
    name = models.CharField(_("Name"), max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    default_debit_coa = models.ForeignKey(
        ChartsOfAccount, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="default_debit_requests", verbose_name=_("Default Debit COA")
    )
    default_credit_coa = models.ForeignKey(
        ChartsOfAccount, null=True, blank=True, on_delete=models.SET_NULL,
        related_name="default_credit_requests", verbose_name=_("Default Credit COA")
    )

    class Meta:
        verbose_name = _("Transaction Request Type")
        verbose_name_plural = _("Transaction Request Types")
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("transrequesttype_detail", kwargs={"pk": self.pk})


class TransactionRequest(TenantAwareModel):
    """
    Pre-approval record for any financial movement.
    When approved, a TransactionDoc + Transactions are created.
    """
    STATUS_CHOICES = [
        ("pending", _("Pending")),
        ("approved", _("Approved")),
        ("rejected", _("Rejected")),
        ("cancelled", _("Cancelled")),
    ]

    transaction_type = models.ForeignKey(
        TransactionRequestType, on_delete=models.PROTECT, related_name="requests"
    )
    description = models.TextField(_("Description"))
    amount = MoneyField(
        _("Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    debit_account = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name="debit_requests", verbose_name=_("Debit Account")
    )
    credit_account = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name="credit_requests", verbose_name=_("Credit Account")
    )
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="pending")
    approving_staff = models.ForeignKey(
        "party.StaffProfile", on_delete=models.PROTECT, related_name="approving_trans_requests"
    )
    transaction_doc = models.ForeignKey(
        TransactionDoc, null=True, blank=True, on_delete=models.CASCADE, related_name="transaction_requests"
    )
    # Source document link
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.UUIDField(null=True, blank=True)
    source_object = GenericForeignKey("content_type", "object_id")

    class Meta:
        verbose_name = _("Transaction Request")
        verbose_name_plural = _("Transaction Requests")
        ordering = ["-created_at"]

    def __str__(self):
        return f"TR {self.id} — {self.amount} ({self.status})"

    def get_absolute_url(self):
        return reverse("transrequest_detail", kwargs={"pk": self.pk})


# ─────────────────────────────────────────────────────────────────────────────
# Invoice & Bill
# ─────────────────────────────────────────────────────────────────────────────

class Invoice(TenantAwareModel):
    """Outbound customer invoice (AR)."""
    STATUS_CHOICES = [
        ("draft", _("Draft")),
        ("sent", _("Sent")),
        ("partially_paid", _("Partially Paid")),
        ("paid", _("Paid")),
        ("overdue", _("Overdue")),
        ("cancelled", _("Cancelled")),
        ("void", _("Void")),
    ]

    invoice_number = models.CharField(_("Invoice Number"), max_length=50, unique=True)
    client = models.ForeignKey(
        "party.ClientProfile", on_delete=models.PROTECT, related_name="invoices", verbose_name=_("Client")
    )
    branch = models.ForeignKey(
        "department.Branch", on_delete=models.PROTECT, related_name="invoices", null=True, blank=True
    )
    issue_date = models.DateField(_("Issue Date"), default=timezone.now)
    due_date = models.DateField(_("Due Date"))
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="draft")
    subtotal = MoneyField(
        _("Subtotal"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    tax_amount = MoneyField(
        _("Tax Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    discount_amount = MoneyField(
        _("Discount Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    total_amount = MoneyField(
        _("Total Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    amount_paid = MoneyField(
        _("Amount Paid"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    notes = models.TextField(blank=True, null=True)
    transaction_doc = models.OneToOneField(
        TransactionDoc, null=True, blank=True, on_delete=models.SET_NULL, related_name="invoice"
    )
    # Polymorphic source (SalesOrder, POSOrder, etc.)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.UUIDField(null=True, blank=True)
    source_document = GenericForeignKey("content_type", "object_id")

    class Meta:
        verbose_name = _("Invoice")
        verbose_name_plural = _("Invoices")
        ordering = ["-issue_date"]

    def __str__(self):
        return f"INV-{self.invoice_number}"

    @property
    def amount_due(self):
        return self.total_amount - self.amount_paid

    def get_absolute_url(self):
        return reverse("invoice_detail", kwargs={"pk": self.pk})


class InvoiceLine(TenantAwareModel):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="lines")
    description = models.CharField(_("Description"), max_length=255)
    quantity = models.DecimalField(_("Quantity"), max_digits=14, decimal_places=4, default=1)
    unit_price = MoneyField(
        _("Unit Price"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    tax = models.ForeignKey(Tax, null=True, blank=True, on_delete=models.SET_NULL, related_name="invoice_lines")
    discount_percent = models.DecimalField(_("Discount %"), max_digits=5, decimal_places=2, default=0)
    line_total = MoneyField(
        _("Line Total"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES, editable=False
    )
    account = models.ForeignKey(Account, null=True, blank=True, on_delete=models.SET_NULL, related_name="invoice_lines")

    class Meta:
        verbose_name = _("Invoice Line")
        verbose_name_plural = _("Invoice Lines")
        ordering = ["invoice"]

    def save(self, *args, **kwargs):
        net = self.unit_price * self.quantity
        discount = net * self.discount_percent / Decimal("100")
        self.line_total = net - discount
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.description} x {self.quantity} = {self.line_total}"


class Bill(TenantAwareModel):
    """Inbound supplier bill (AP)."""
    STATUS_CHOICES = [
        ("draft", _("Draft")),
        ("received", _("Received")),
        ("partially_paid", _("Partially Paid")),
        ("paid", _("Paid")),
        ("overdue", _("Overdue")),
        ("disputed", _("Disputed")),
        ("cancelled", _("Cancelled")),
    ]

    bill_number = models.CharField(_("Bill Number"), max_length=100)
    supplier = models.ForeignKey(
        "party.SupplierProfile", on_delete=models.PROTECT, related_name="bills"
    )
    branch = models.ForeignKey(
        "department.Branch", on_delete=models.PROTECT, related_name="bills", null=True, blank=True
    )
    issue_date = models.DateField(_("Bill Date"), default=timezone.now)
    due_date = models.DateField(_("Due Date"))
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="draft")
    subtotal = MoneyField(
        _("Subtotal"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    tax_amount = MoneyField(
        _("Tax Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    total_amount = MoneyField(
        _("Total Amount"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    amount_paid = MoneyField(
        _("Amount Paid"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    notes = models.TextField(blank=True, null=True)
    transaction_doc = models.OneToOneField(
        TransactionDoc, null=True, blank=True, on_delete=models.SET_NULL, related_name="bill"
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.UUIDField(null=True, blank=True)
    source_document = GenericForeignKey("content_type", "object_id")

    class Meta:
        verbose_name = _("Bill")
        verbose_name_plural = _("Bills")
        unique_together = ("bill_number", "supplier")
        ordering = ["-issue_date"]

    def __str__(self):
        return f"BILL-{self.bill_number} from {self.supplier}"

    @property
    def amount_due(self):
        return self.total_amount - self.amount_paid

    def get_absolute_url(self):
        return reverse("bill_detail", kwargs={"pk": self.pk})


class BillLine(TenantAwareModel):
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE, related_name="lines")
    description = models.CharField(_("Description"), max_length=255)
    quantity = models.DecimalField(_("Quantity"), max_digits=14, decimal_places=4, default=1)
    unit_price = MoneyField(
        _("Unit Price"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES
    )
    tax = models.ForeignKey(Tax, null=True, blank=True, on_delete=models.SET_NULL, related_name="bill_lines")
    line_total = MoneyField(
        _("Line Total"), max_digits=20, decimal_places=2,
        default=0, default_currency=DEFAULT_CURRENCY, currency_choices=CURRENCY_CHOICES, editable=False
    )
    account = models.ForeignKey(Account, null=True, blank=True, on_delete=models.SET_NULL, related_name="bill_lines")

    class Meta:
        verbose_name = _("Bill Line")
        verbose_name_plural = _("Bill Lines")

    def save(self, *args, **kwargs):
        self.line_total = self.unit_price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.description} x {self.quantity} = {self.line_total}"


# ─────────────────────────────────────────────────────────────────────────────
# Post-save signals — auto-create Account entries
# ─────────────────────────────────────────────────────────────────────────────

def _resolveid(instance):
    """Return the UUID primary key of instance, traversing Staff wrapping."""
    for attr in ("id", "pk"):
        val = getattr(instance, attr, None)
        if val:
            return val
    return None


def _resolve_company(instance):
    """Walk common relationship chains to find the Company for an instance."""
    chains = [
        ["company"],
        ["branch", "department", "company"],
        ["department", "company"],
        ["staff", "company"],
    ]
    for chain in chains:
        current = instance
        for attr in chain:
            current = getattr(current, attr, None)
            if current is None:
                break
        if current:
            return current
    return None


@receiver(post_save, sender=Tax)
@receiver(post_save, sender=Bank)
@receiver(post_save, sender=BankAccount)
def create_account_instance(sender, instance, created, **kwargs):
    """Auto-create linked Account entries for financial entities."""
    if not created:
        return
    id_val = _resolveid(instance)
    ct = ContentType.objects.get_for_model(sender)
    model_name = ct.model  # lowercase

    try:
        if model_name == "tax":
            payable_coa = ChartsOfAccount.objects.get(name="Taxes Payable")
            expense_coa = ChartsOfAccount.objects.get(name="Tax Expense")
            payable_acc, _ = Account.objects.get_or_create(
                content_type=ct, object_id=id_val, account_type=payable_coa
            )
            expense_acc, _ = Account.objects.get_or_create(
                content_type=ct, object_id=id_val, account_type=expense_coa
            )
            Tax.objects.filter(pk=id_val).update(
                tax_payable_account=payable_acc,
                tax_expense_account=expense_acc,
            )

        elif model_name == "bank":
            notes_coa = ChartsOfAccount.objects.get(name="Notes Payable")
            interest_coa = ChartsOfAccount.objects.get(name="Interest Payable")
            notes_acc, _ = Account.objects.get_or_create(
                content_type=ct, object_id=id_val, account_type=notes_coa
            )
            interest_acc, _ = Account.objects.get_or_create(
                content_type=ct, object_id=id_val, account_type=interest_coa
            )
            Bank.objects.filter(pk=id_val).update(
                notes_payable_account=notes_acc,
                notes_interest_account=interest_acc,
            )

        elif model_name == "bankaccount":
            current_asset_coa = ChartsOfAccount.objects.get(name="Current Asset")
            cash_acc, _ = Account.objects.get_or_create(
                content_type=ct, object_id=id_val, account_type=current_asset_coa
            )
            BankAccount.objects.filter(pk=id_val).update(cash_account=cash_acc)

    except Exception as exc:
        raise ValidationError(
            _(f"Could not create ledger account for {sender.__name__}: {exc}. "
              "Ensure the Chart of Accounts has been initialised.")
        )


# Branch and user profile account creation is handled via signals registered
# in the post_save handlers below (imported lazily to avoid circular imports).

@receiver(post_save)
def create_branch_and_profile_accounts(sender, instance, created, **kwargs):
    """Lazy handler — Branch + profiles trigger account creation."""
    if not created:
        return
    from django.apps import apps
    BranchModel = apps.get_model("party", "Branch")
    StaffProfileModel = apps.get_model("party", "StaffProfile")
    ClientProfileModel = apps.get_model("party", "ClientProfile")
    SupplierProfileModel = apps.get_model("party", "SupplierProfile")

    if not isinstance(instance, (BranchModel, StaffProfileModel, ClientProfileModel, SupplierProfileModel)):
        return

    ct = ContentType.objects.get_for_model(sender)
    id_val = _resolveid(instance)

    try:
        if isinstance(instance, BranchModel):
            _create_branch_accounts(ct, id_val, instance)
        elif isinstance(instance, StaffProfileModel):
            _create_staff_accounts(ct, id_val, instance)
        elif isinstance(instance, ClientProfileModel):
            _create_client_accounts(ct, id_val, instance)
        elif isinstance(instance, SupplierProfileModel):
            _create_supplier_accounts(ct, id_val, instance)
    except Exception as exc:
        raise ValidationError(
            _(f"Could not create ledger account for {sender.__name__}: {exc}")
        )


def _create_branch_accounts(ct, id_val, instance):
    account_names = {
        "Assets": ["Inventory", "Accounts Receivables", "Cash"],
        "Liabilities": ["Accounts Payable", "Wages Payable", "Tips Payable"],
        "Capital/Equity": ["Capital"],
        "Revenues/Income": ["Revenue/Income", "Operational Income"],
        "Expenses": ["Regular Expense", "Depreciation Expense", "Marketing Expenses",
                     "Freight Expense", "Cost of Goods Sold"],
    }
    accounts_list = []
    for acct_type, names in account_names.items():
        for name in names:
            coa = ChartsOfAccount.objects.get(name=name, account_type=acct_type)
            acc, _ = Account.objects.get_or_create(
                content_type=ct, object_id=id_val, account_type=coa
            )
            accounts_list.append(acc)
    from apps.party.models import Branch
    branch = Branch.objects.get(pk=id_val)
    branch.branch_accounts.set(accounts_list)


def _create_staff_accounts(ct, id_val, instance):
    coa = ChartsOfAccount.objects.get(name="Payroll Expenses")
    staff_acc, _ = Account.objects.get_or_create(content_type=ct, object_id=id_val, account_type=coa)
    ar_coa = ChartsOfAccount.objects.get(name="Accounts Receivables")
    ar_acc, _ = Account.objects.get_or_create(content_type=ct, object_id=id_val, account_type=ar_coa)
    from apps.party.models import StaffProfile
    StaffProfile.objects.filter(pk=id_val).update(staff_account=staff_acc, credit_sale_account=ar_acc)


def _create_client_accounts(ct, id_val, instance):
    coa = ChartsOfAccount.objects.get(name="Accounts Receivables")
    acc = Account.objects.create(content_type=ct, object_id=id_val, account_type=coa)
    from apps.party.models import ClientProfile
    ClientProfile.objects.filter(pk=id_val).update(client_account=acc)


def _create_supplier_accounts(ct, id_val, instance):
    coa = ChartsOfAccount.objects.get(name="Accounts Payable")
    acc = Account.objects.create(content_type=ct, object_id=id_val, account_type=coa)
    from apps.party.models import SupplierProfile
    SupplierProfile.objects.filter(pk=id_val).update(vendor_account=acc)


# ─────────────────────────────────────────────────────────────────────────────
# Bootstrap COA for new Company tenant
# ─────────────────────────────────────────────────────────────────────────────

@receiver(post_save)
def load_initial_account_data(sender, instance, created, **kwargs):
    """
    When a new Company is created, bulk-create the default Chart of Accounts
    and load Occupation data from ISCO-08 Excel if available.
    """
    if not created:
        return
    from django.apps import apps
    try:
        CompanyModel = apps.get_model("party", "Company")
    except LookupError:
        return
    if not isinstance(instance, CompanyModel):
        return

    ASSETS = (
        "Cash", "Accounts Receivables", "Inventory", "Prepaid Expense",
        "Other Liquid Assets", "Notes Receivable", "Current Asset",
        "Land", "Securities", "Buildings", "Buildings - Accum. Depreciation",
        "Plant", "Vehicles - Accum. Depreciation", "Vehicles",
        "Plant - Accum. Depreciation", "Equipment", "Supplies",
        "Equipment - Accum. Depreciation", "Intangible Assets",
        "Intangible Assets - Accum. Amortization", "Other Assets",
    )
    LIABILITIES = (
        "Accounts Payable", "Wages Payable", "Interest Payable", "Taxes Payable",
        "Notes Payable", "Prepaid Income", "Deferred Revenue", "Other Liabilities",
        "Bonds Payable", "Mortgage Payable", "Discount on Bonds Payable", "Tips Payable",
    )
    EQUITY = (
        "Capital", "Common Stock", "Preferred Stock", "Retained Earnings",
        "Treasury Stock", "Other Equity Adjustments", "Dividends & Distributions to Shareholders",
    )
    REVENUES = (
        "Revenue/Income", "Operational Income", "Investing/Passive Income", "Interest Income",
        "Capital Gain/Loss Income", "Income_Other", "Interest Revenue",
    )
    EXPENSES = (
        "Regular Expense", "Freight Expense", "Interest Expense", "Tax Expense",
        "Capital Expense", "Depreciation Expense", "Amortization Expense",
        "Other Expense", "Marketing Expenses", "Payroll Expenses", "Cost of Goods Sold",
    )

    series = {
        "Assets": (10100000, "Debit"),
        "Liabilities": (20100000, "Credit"),
        "Capital/Equity": (30100000, "Credit"),
        "Revenues/Income": (40100000, "Credit"),
        "Expenses": (50100000, "Debit"),
    }
    data = {
        "Assets": ASSETS,
        "Liabilities": LIABILITIES,
        "Capital/Equity": EQUITY,
        "Revenues/Income": REVENUES,
        "Expenses": EXPENSES,
    }

    for acct_type, names in data.items():
        start, balance = series[acct_type]
        step = 1000 if acct_type in ("Assets", "Capital/Equity", "Revenues/Income") else 2000
        entries = [
            ChartsOfAccount(
                account_type=acct_type,
                account_balance_type=balance,
                name=name,
                acc_number=start + i * step,
            )
            for i, name in enumerate(names)
        ]
        ChartsOfAccount.objects.bulk_create(entries, ignore_conflicts=True)

    # Bootstrap address types
    from django.apps import apps as dj_apps
    try:
        AddressTypeModel = dj_apps.get_model("party", "AddressType") if False else None
    except Exception:
        pass

    # Load occupations from ISCO-08
    try:
        import pandas as pd
        from apps.party.models import Occupation
        roles = pd.read_excel("./data/ISCO-08 EN Structure and definitions.xlsx",
                              sheet_name="ISCO-08 EN Struct and defin")
        for _, row in roles.drop_duplicates().iterrows():
            try:
                Occupation.objects.update_or_create(
                    name=str(row.get("Title EN", "")).capitalize(),
                    defaults={
                        "definition": str(row.get("Definition", "")),
                        "task": str(row.get("Tasks include", "")),
                    },
                )
            except Exception:
                continue
    except Exception:
        pass
